### ISSUE TITLE
allow default parameters when creating and updating actions

### ISSUE THREAD

**Issue by aslom** [openwhisk/openwhisk-client-js#11]
action.js does not allow to set {"parameters"}
 
```
wsk -v action create --kind nodejs:6 -p param pval helloAction7 helloAction.js
...
Body sent:
{"parameters": [{"value": "pval", "key": "param"}], "exec": {"kind": "nodejs:6", "code": "function main() {\n    return {payload: 'Hello world'};\n}\n"}}
```

**Comment by jthomas** [comment]
If you want to see default parameters whilst creating an action, you need to send the entire action object body, rather than just the source string. 
https://github.com/openwhisk/openwhisk-client-js/blob/master/lib/actions.js#L75-L77

```
var action = {
  exec: {kind: 'nodejs:default', code: '...'}, 
  parameters: [{key: "some_key", value: "some_value"}]
}
ow.actions.create({actionName: '...', action: action})
```

I know this isn't clear from the README, I'll make a note to update it.
